# Generated by Django 4.1.2 on 2023-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('anatasoin', models.CharField(max_length=255)),
                ('yaer', models.IntegerField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
