# Generated by Django 4.1.2 on 2023-02-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='yaer',
            new_name='year',
        ),
    ]
