# Generated by Django 4.1.2 on 2023-02-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='год выпуска'),
        ),
    ]
